### ISSUE TITLE
Add functionality to specify schema

### ISSUE THREAD

**Issue by joosthooz** [conbench/datalogistik#36]
Add code to read the schema from the datasources repo file, or possibly even allow users to specify a certain schema.

**Comment by alistaire47** [comment]
Is there a good/preferred way of saving schemas? It'd be really nice if we could take them to/from json, but thus far I haven't seen a reasonably robust way of doing so

**Comment by alistaire47** [comment]
We might need to go a little deeper than that for fields with options, e.g. unit/timezone for timestamps and precision/scale for decimal. Maybe just optional kwargs that can be passed through like

```json
{
  "id": {"type_name": "string"},
  "click_ts": {"type_name": "timestamp", "type_args": {"unit": "ms"}},
  "some_value": {"type_name": "decimal128", "type_args": {"precision": 7, "index": 3}},
  ...
}
```

Or flat or otherwise—I don't really care about arrangement, just that it's flexible enough when we need it

**Comment by joosthooz** [comment]
This is a really good point, I'm copying this into the PR so I can easily find it, thanks!

**Comment by joosthooz** [comment]
PR: #41

**Comment by jonkeane** [comment]
I haven't dug too deeply into the PR yet, but https://github.com/apache/arrow/issues/13803 has some discussion about this from the Arrow perspective + some links to how this (apparently?) works in Rust. We certainly would benefit from following that as closely as possible (or possibly upstreaming the work | reigniting the conversation on the ML, etc if we think it's important to push into Arrow itself).

https://github.com/apache/arrow/pull/7110 also had a PR to do some of this as well (though it was closed due to a lack of pushing forward + enthusiasm).

**Comment by joosthooz** [comment]
Thanks @jonkeane , it seems there are more people trying to build more or less this same thing. Maybe I can just translate this piece of code to python https://github.com/apache/arrow-rs/blob/27f4762c8794ef1c5d042933562185980eb85ae5/arrow/src/datatypes/datatype.rs#L785 . If it ends up becoming part of Arrow itself, we can always convert to just calling the API function.

**Comment by jonkeane** [comment]
> If it ends up becoming part of Arrow itself, we can always convert to just calling the API function.

💯 absolutely. We also do have a slightly more constrained scope than arrow, so it's possible the rabbit hole of "what to do about embedded types" won't be so bad for us?

**Comment by joosthooz** [comment]
Ok I made an improvement I think has a nice balance. The current code supports types with arguments, as long as the user just uses the same keywords for them as pyarrow does. Because it will just pass the dict containing the args as a **kwargs.
It doesn't support nested types at all. I think adding that wouldn't even be that complex, but I'm also ok with keeping that unsupported.
A type with args would look like this:
```
"click_ts": {"name": "timestamp", "arguments": {"unit": "ms"}},
```
