### ISSUE TITLE
Make a __post_init__() method for some value checking + default setting?

### ISSUE THREAD

**Issue by jonkeane** [conbench/datalogistik#69]
For example, we probably want to ensure the following all are valid values:
  * format
  * scale_factor
  * compression
  * partitioning (later)

**Comment by alistaire47** [comment]
You can do this with properties instead of a `__post_init__()`, which has the benefit of also running if an attribute is overridden after initialization, though making it work with dataclasses requires a tad more boilerplate: https://stackoverflow.com/questions/51079503/dataclasses-and-property-decorator

**Comment by joosthooz** [comment]
We have a `__post_init` method that performs checks as best it can: https://github.com/conbench/datalogistik/blob/525914518907458eb32d188d42b986bfa7fc605d/datalogistik/dataset.py#L79 .
Note that it is not trivial to do this for all situations, because sometimes we would like to e.g. use a setting for a dataset in the cache.
