### ISSUE TITLE
Move `header_line` to Table

### ISSUE THREAD

**Issue by jonkeane** [conbench/datalogistik#76]
And also ensure that it's default setting makes sense + it is used correctly

**Comment by jonkeane** [comment]
> If a user-specified schema is found, there would usually not be a header line too (but it should be possible - in this case which names would be used?)

Agreed this is a tendency, though it's definitely not consistently always the case like you mention in your parenthetical

**Comment by alistaire47** [comment]
> > If a user-specified schema is found, there would usually not be a header line too (but it should be possible - in this case which names would be used?)
> 
> Agreed this is a tendency, though it's definitely not consistently always the case like you mention in your parenthetical

Yeah, I don't think you can take this for granted, especially when dealing with CSVs and such where you might be using a schema to specify precision or whatever for a dataset written by someone else.



> * Passing a schema is not enough; you also need to separately supply the column names (even though they are also stored in the schema).

In [voltrondata-labs/benchmarks we just grabbed column names from the schema](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_sources.py#L337); otherwise you have to handle the case where they don't line up
